version: "3.9"

services:
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    image: "mysql:8"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"