app:
  version: @project.version@

java:
  version: @java.version@

logging:
  level:
    root: info

spring:
  application:
    name: Spring-Boot-Todo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:todo}?autoreconnect=true"
    password: "${DATABASE_USER:root}"
    username: "${DATABASE_PASSWORD:root}"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  flyway:
    enabled: true
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/mysql
    schemas: "${DATABASE_NAME:todo}"
    user: "${FLYWAY_DATABASE_USER:root}"
    password: "${FLYWAY_DATABASE_PASSWORD:root}"

